# Generated by Django 4.0.3 on 2022-03-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchlist',
        ),
    ]
