# Generated by Django 4.0.3 on 2022-03-25 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='searchlist',
            new_name='Resultlist',
        ),
    ]
