# Generated by Django 4.0.3 on 2022-03-25 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0004_rename_searchlist_resultlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultlist',
        ),
    ]
