# Generated by Django 4.0.3 on 2022-03-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resultlist',
        ),
    ]
